# Generated by Django 5.2.5 on 2025-09-15 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadocesar.armazem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadocesar.produto')),
            ],
            options={
                'unique_together': {('produto', 'armazem')},
            },
        ),
    ]
