# Generated by Django 5.2.6 on 2025-09-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0003_produto_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armazem',
            options={'verbose_name_plural': 'Armazéns'},
        ),
    ]
