# Generated by Django 5.2.6 on 2025-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0004_alter_armazem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
