# Generated by Django 5.2.6 on 2025-10-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0005_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('codigo', ''), _negated=True), name='codigo_nao_vazio'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('categoria', ''), _negated=True), name='categoria_nao_vazia'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('unidade_medida', ''), _negated=True), name='unidade_medida_nao_vazia'),
        ),
    ]
