# Generated by Django 5.2.6 on 2025-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0006_produto_codigo_nao_vazio_produto_categoria_nao_vazia_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('descricao', ''), _negated=True), name='descricao_nao_vazia'),
        ),
    ]
