# Generated by Django 5.2.6 on 2025-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0008_alter_produto_preco_custo_alter_produto_preco_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_venda',
            new_name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='PRODUTO SEM NOME', max_length=30, unique=False),
            preserve_default=False,
        ),
    ]
