# Generated by Django 5.2.6 on 2025-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0009_rename_preco_venda_produto_preco_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
