# Generated by Django 5.2.6 on 2025-10-19 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0010_alter_produto_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandeira', models.CharField(max_length=20)),
                ('ultimos_4_digitos', models.CharField(max_length=4)),
                ('mes_validade', models.IntegerField()),
                ('ano_validade', models.IntegerField()),
                ('apelido', models.CharField(blank=True, help_text='Ex: Cartão Principal', max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
    ]
