# Generated by Django 5.2.6 on 2025-10-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0014_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mercadocesar.cartaocredito'),
        ),
    ]
