# Generated by Django 5.2.6 on 2025-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0015_pedido_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Imagem do Produto'),
        ),
    ]
