# Generated by Django 5.2.6 on 2025-11-14 19:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadocesar', '0019_resalvar_imagens_cloudinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
