name: Deploy Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      run_e2e_tests:
        description: 'Executar testes E2E?'
        required: false
        default: false
        type: boolean

jobs:
  e2e-tests:
    name: E2E Tests 
    runs-on: ubuntu-latest
    if: github.event.inputs.run_e2e_tests == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Setup Django environment
      run: |
        echo "SECRET_KEY=test-secret-key-e2e" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
    
    - name: Prepare Django app
      run: |
        python manage.py migrate
        python manage.py collectstatic --noinput
        # Criar superuser para testes
        python manage.py shell -c "
        from django.contrib.auth import get_user_model;
        User = get_user_model();
        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@test.com', 'admin123')
        "
    
    - name: Start Django server
      run: |
        python manage.py runserver &
        sleep 5
        echo "Django server started"
    
    - name: Run E2E Tests
      run: |
        for test_file in mercadocesar/selenium/e2e/*.py; do
          if [ -f "$test_file" ]; then
            echo "Running test: $test_file"
            python "$test_file"
          fi
        done
        echo "E2E tests completed"

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [e2e-tests]
    if: always() && github.ref == 'refs/heads/main'

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} 
          api-key: ${{ secrets.RENDER_API_KEY }}